### ISSUE TITLE
Preliminary login process for Data Sponsors

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tiger-data-app#112]
### User Story
As Data Sponsor, I need to sign in to TigerData, so that I can review my sponsored projects.

### User Journey Images
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/539521ac-69bb-454b-bd3d-b8326f84ac1f)
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/7bf88c66-f640-41f5-bade-5da1ec0b389e)
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/b514977c-2faf-413d-97de-47ff9a4e413d)
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/7ce2bcf1-c86b-4bbe-b672-7fc9204ed942)

(Slides 7-10 in [TigerData_PresLayer_UserJourneys_v0.8_2023-09-27.pdf](https://drive.google.com/file/d/19ElNGrSLzOGCOw2yjzdAoHZ8egBVg4EO/view?usp=drive_link))

### Completion Criteria

- [x] A preliminary TigerData home page is live for early testers (e.g. tigerdata-staging.princeton.edu)
- [x] The home page contains the TigerData logo, a "Welcome to TigerData" message, and a "Login" button
- [x] Clicking the login button takes one to CAS
- [x] Successfully authenticating with CAS triggers a backend check for TigerData registration (using a list of NetIDs for early adopters maintained by the Product Owner)
- [x] If one is not registered, then one is taken to a preliminary help page (e.g. tigerdata-staging.princeton.edu/help) with a message that says "TigerData is still under construction, and you are not registered as a tester at this time. If you have any questions, please contact the team at tigerdata@princeton.edu."
- [x] If one is verified as registered, then one is taken to a preliminary dashboard page (e.g. tigerdata-staging.princeton.edu/dashboard)
- [x] The top of the preliminary dashboard page contains the TigerData logo, a placeholder welcome message, and a "Logout" button
- [x] The body of the preliminary dashboard page contains a section titled "My Projects" that includes a heading of "Sponsored by Me" followed by a placeholder set of project titles (links inactive), and a placeholder "New Project" button (inactive) below the list of project titles

**Comment by matthewjchandler** [comment]
@hectorcorrea It looks like #173 completes the last criterion, but I'd like to check in with you and the team about it on Nov. 29, 2023

**Comment by matthewjchandler** [comment]
Reviewed in feature refinement on January 17, 2024, and everything looks good!
