### ISSUE TITLE
Preliminary project creation form

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tiger-data-app#113]
### User Story
As a Data Sponsor, I need to create a new project, so that I can start moving files into TigerData storage.

### User Journey Images
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/059b0cd8-acfc-4d78-852e-7e84e726de67)
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/896a6bc7-aeb0-46ea-9dda-80d7ea60b01d)
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/bac39ef1-e67e-4635-bf16-09dd080e1c51)
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/8e115ea8-665c-482c-aa3e-f3b600bb9f8e)
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/403f60cc-42c9-460c-9434-6e4c05591122)
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/fdbd6c26-9134-47aa-a8d5-e91c767b673b)
(Slides 11-16 in [TigerData_PresLayer_UserJourneys_v0.8_2023-09-27.pdf](https://drive.google.com/file/d/19ElNGrSLzOGCOw2yjzdAoHZ8egBVg4EO/view?usp=drive_link))

### Supplemental Materials
[TigerData Standard Metadata Schema Draft v0.5](https://docs.google.com/document/d/1XjXkzhs5ngM5cmyrmTLaIxG6TF4jT7-HMsMrjj3akRw)

### Completion Criteria

- [x] Launch new project request from dashboard
  - [x] On the preliminary dashboard page, clicking the "New Project" button takes one to a preliminary "New Project" form
- [x] Preliminary new project request form framework
  - [x] The title of the form page is "New Project Request" [#340](https://github.com/pulibrary/tiger-data-app/issues/340)
  - [x] The form's data entry fields are organized into two sections
  - [x] The first section of the form is labeled "Roles" and contains three fields: "Data Sponsor", "Data Manager", and "Data User(s)"
  - [x] The second section of the form is labeled "Description" and contains four fields: "Affiliated Department(s)", "Project Directory", "Title", and "Description"
  - [x] #251
- [x] Role fields data entry and validation
  - [x] #285
  - [x] #252
  - [x] The "Data Manager" field is required, singular, and accepts the NetID of a preliminary tester as a value
  - [x] The "Data User(s)" field is optional, multiple, and accepts the NetIDs of preliminary testers as values
  - [x] The "Data User(s)" may be entered as comma-separated NetIDs in either a "Read Only" text box or a "Read/Write" text box
- [x] Description fields data entry and validation
  - [x] The "Affiliated Department(s)" field is required, singular, and can only be filled from a multiselect module containing a list of valid departments (supplied by the Product Owner)
  - [x] #253
  - [x] The "Title" field is required, singular, and accepts a Unicode string value with no character restrictions or limits
  - [x] #254
- [x] Preliminary new project request form direct actions
  - [x] #255
  - [x] #256
  - [x] #257
  - [x] #287
    - [x] [#336](https://github.com/pulibrary/tiger-data-app/issues/336)
    - [x] #258
- [x] #259
  - [x] #260
- [x] #261

**Comment by hectorcorrea** [comment]
See Tickets
* https://github.com/pulibrary/tiger-data-app/issues/169
* https://github.com/pulibrary/tiger-data-app/issues/170
* https://github.com/pulibrary/tiger-data-app/issues/171
* https://github.com/pulibrary/tiger-data-app/issues/172
* https://github.com/pulibrary/tiger-data-app/issues/173

**Comment by matthewjchandler** [comment]
Reviewed in feature refinement on January 17, 2024, and it looks good!
