### ISSUE TITLE
Project revision request confirmation page

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tiger-data-app#277]
### User Story
As a Data Manager, when I make a project revision request, I need confirmation that my request went through and is being processed, so that I can move on to my next task.

### Notes
After changes have been entered and validated and the user clicks the "Submit" button on the "Project Revision Request" form,  then the user should be taken to the "Project Revision Request Received" page, which contains the same message and button as the "New Project Request Received" page.

### Completion Criteria
- [ ] Successfully submitting a new project request (#275) brings the user to this confirmation page
- [ ] The page is titled "Project Revision Request Received"
- [ ] The message body is the same as that from #259 (for now)
- [ ] This is a new page that is a copy of the page for #259 so that we can change the text independently
- [ ] Below the message is a "Return to Dashboard" button

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/277?planning-poker) with Zenhub @bess @JaymeeH @jrgriffiniii @leefaisonr
