### ISSUE TITLE
Role emulation for Tester-Trainers

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tiger-data-app#554]
–### User Story
As a data management trainer, I need to emulate other roles in a QA environment, so that I can demonstrate how the presentation layer works for Data Manager trainees.

### Context
In order to become eligible for the Data Manager role, one must complete data management training. These are 3-hour hands-on sessions in which TigerData users learn how the systems work and how to use them according to the best practices of data management. The trainers need to show everyone how the presentation layer looks for different roles, and trainees need to try their hands at creating new projects and revising projects. Furthermore, the trainers need to emulate system administrators to approve test projects and revisions, so that the trainees can try out post-approval operations.

Building emulation capabilities for trainers has the added benefit of allowing me to test role-specific features as we build them. Down the road, I expect others will need to perform tests in the QA environment as well.

This is all different from being a super-user or a system administrator. The tester-trainer role should give the ability to emulate other roles in the Presentation Layer, including Data Sponsor, Data Manager, Data User, and System Administrator, for the purposes of quality assurance and training Data Managers. While emulating another role, the Tester-Trainer is capable of performing actions only on Quality Assurance instances of the Presentation Layer (possibly with effects on corresponding development/staging instances of the Middle Layer), and not on any production systems.

Refer to [TigerData Role Eligibility Definitions](https://docs.google.com/document/d/1OyOLTd_jMqszRbN_vPhAC_lDB-p4E8czxAGM55Z1FbU).

### Completion Criteria
- [x] #618
- [x] (covered by #618) Assign the tester-trainer role to specific users according to the "tester_trainer" column in the [preliminary registration list](https://docs.google.com/spreadsheets/d/169lfRTOSe6H66Iu2DK5g-QzqiVsfz5lHFHMaGmwNT7Y)
- [x] #619
- [ ] (covered by #619)While emulating another role, the tester-trainer may perform only the actions specified for the emulated role
- [ ] (covered by #619) Emulation works in the Staging/QA environment only; emulated actions never have any effects in production systems
- [x] #620
  - [ ] Eligible Data Sponsor
  - [ ] Eligible Data Manager
  - [ ] Eligible Data User
  - [ ] System Administrator
  - [ ] Return to Self
- [ ] [Allow a fixture data set to show the user the different projects from all angles Assigned Data Sponsor, Assigned Data Manager, and Assigned Data User, and vanilla project where the user is not assigned any role.  These will all be approved](https://github.com/pulibrary/tiger-data-app/issues/616)
- [ ] (coverd by #616) fixture data that is pending for the system administrator (could be the vanilla project above
- [ ] When I am not eligible I should not see fixtures on my dashboard for things like sponsored by me
- [ ] Eligible roles from the selection list mean eligible but not necessarily assigned currently to any and all projects.  There should be the fixture project showing at a minimum
- [ ] The fixture data should be set up so that no matter which role I am emulating I see something on my dashboard
- [ ] There should be a bar across the top that has the drop down menu and it clearly shows who I am currently seeing this as

**Comment by matthewjchandler** [comment]
We'll need enhancement on this later, pending refined designs, but for now, I'm marking the epic as complete
